# Generated by Django 5.0.7 on 2024-07-13 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('offer', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images/product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
